version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"  # Updated port mapping
    networks:
      - webnet
    volumes:
      - ./frontend/vite.config.ts:/app/vite.config.ts

networks:
  webnet:
