version: '3.8'

services:
  api:
    image: api_image
    build:
      context: ./api
    volumes:
      - ./database:/app/database
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app/database/users.db
